import type { Category, CategorySlug, Tool, Review, User } from '@/types'

export const CATEGORIES: Category[] = [
  {
    slug: 'frontend',
    name: 'Frontend',
    description: 'UI frameworks, libraries, and tools for building user interfaces',
    icon: 'RiLayoutLine',
    color: 'text-blue-400',
  },
  {
    slug: 'backend',
    name: 'Backend',
    description: 'Server-side frameworks, APIs, and backend services',
    icon: 'RiServerLine',
    color: 'text-violet-400',
  },
  {
    slug: 'database',
    name: 'Database',
    description: 'Database systems, ORMs, and data management tools',
    icon: 'RiDatabase2Line',
    color: 'text-emerald-400',
  },
  {
    slug: 'devops',
    name: 'DevOps',
    description: 'CI/CD, containerization, and infrastructure tools',
    icon: 'RiGitBranchLine',
    color: 'text-orange-400',
  },
  {
    slug: 'cloud',
    name: 'Cloud',
    description: 'Cloud platforms and cloud-native services',
    icon: 'RiCloudLine',
    color: 'text-sky-400',
  },
  {
    slug: 'mobile',
    name: 'Mobile',
    description: 'Mobile development frameworks and tools',
    icon: 'RiSmartphoneLine',
    color: 'text-pink-400',
  },
  {
    slug: 'ai',
    name: 'AI / ML',
    description: 'Machine learning, AI APIs, and LLM tools',
    icon: 'RiBrainLine',
    color: 'text-yellow-400',
  },
  {
    slug: 'testing',
    name: 'Testing',
    description: 'Testing frameworks, tools, and quality assurance',
    icon: 'RiTestTubeLine',
    color: 'text-red-400',
  },
  {
    slug: 'design',
    name: 'Design',
    description: 'Design tools, UI kits, and prototyping platforms',
    icon: 'RiPaletteLine',
    color: 'text-fuchsia-400',
  },
]

export const ALL_TOOLS: Tool[] = [
  {
    id: '1',
    name: 'React',
    slug: 'react',
    description: 'A JavaScript library for building user interfaces with a component-based architecture',
    longDescription:
      'React is a declarative, efficient, and flexible JavaScript library for building user interfaces. It lets you compose complex UIs from small and isolated pieces of code called "components". React is maintained by Meta and a large community of individual developers and companies.',
    category: 'frontend',
    websiteUrl: 'https://react.dev',
    githubUrl: 'https://github.com/facebook/react',
    avgRating: 4.8,
    totalReviews: 1247,
    pros: [
      'Huge ecosystem and community support',
      'Reusable component architecture',
      'Excellent developer tools (DevTools, profiler)',
      'Strong TypeScript support',
      'Virtual DOM for performant updates',
    ],
    cons: [
      'Steep learning curve for beginners',
      'JSX can feel unusual at first',
      'Requires additional libraries for routing/state',
      'Frequent breaking changes between major versions',
    ],
  },
  {
    id: '2',
    name: 'Next.js',
    slug: 'nextjs',
    description: 'The React framework for production with hybrid static and server rendering',
    longDescription:
      'Next.js gives you the best developer experience with all the features you need for production: hybrid static and server rendering, TypeScript support, smart bundling, route pre-fetching, and more.',
    category: 'frontend',
    websiteUrl: 'https://nextjs.org',
    githubUrl: 'https://github.com/vercel/next.js',
    avgRating: 4.7,
    totalReviews: 983,
    pros: [
      'File-based routing is intuitive',
      'Built-in SSR and SSG support',
      'Excellent performance out of the box',
      'Image and font optimization',
      'API routes included',
    ],
    cons: [
      'Vendor lock-in with Vercel ecosystem',
      'App Router has a steep learning curve',
      'Large bundle size for simple apps',
      'Configuration can be complex',
    ],
  },
  {
    id: '3',
    name: 'Supabase',
    slug: 'supabase',
    description: 'Open source Firebase alternative with a PostgreSQL database',
    longDescription:
      'Supabase is an open source Firebase alternative. Start your project with a Postgres database, Authentication, instant APIs, Edge Functions, Realtime subscriptions, Storage, and Vector embeddings.',
    category: 'backend',
    websiteUrl: 'https://supabase.com',
    githubUrl: 'https://github.com/supabase/supabase',
    avgRating: 4.9,
    totalReviews: 756,
    pros: [
      'Full PostgreSQL power with a great UI',
      'Built-in auth with multiple providers',
      'Realtime subscriptions out of the box',
      'Generous free tier',
      'Open source and self-hostable',
    ],
    cons: [
      'Can be expensive at scale',
      'Edge Functions limited compared to alternatives',
      'Dashboard can be slow to load',
    ],
  },
  {
    id: '4',
    name: 'Tailwind CSS',
    slug: 'tailwind-css',
    description: 'A utility-first CSS framework for rapidly building custom user interfaces',
    longDescription:
      'Tailwind CSS is a utility-first CSS framework packed with classes that can be composed to build any design, directly in your markup.',
    category: 'frontend',
    websiteUrl: 'https://tailwindcss.com',
    githubUrl: 'https://github.com/tailwindlabs/tailwindcss',
    avgRating: 4.6,
    totalReviews: 1089,
    pros: [
      'Extremely fast prototyping',
      'No context switching between CSS and HTML',
      'Highly customizable design system',
      'Tiny production bundle with PurgeCSS',
      'Excellent IntelliSense plugin',
    ],
    cons: [
      'HTML can become cluttered with classes',
      'Learning all utility names takes time',
      'Opinionated — hard to escape the paradigm',
      'Not ideal for complex animations',
    ],
  },
  {
    id: '5',
    name: 'Docker',
    slug: 'docker',
    description: 'Platform for developing, shipping, and running applications in containers',
    longDescription:
      'Docker enables you to separate your applications from your infrastructure so you can deliver software quickly.',
    category: 'devops',
    websiteUrl: 'https://www.docker.com',
    githubUrl: 'https://github.com/docker/cli',
    avgRating: 4.5,
    totalReviews: 892,
    pros: [
      '"Works on my machine" problem solved forever',
      'Consistent environments across dev/staging/prod',
      'Huge image registry (Docker Hub)',
      'Great for microservices architecture',
      'Easy horizontal scaling',
    ],
    cons: [
      'High memory/CPU overhead per container',
      'Networking configuration can be complex',
      'Desktop version is slow on macOS',
      'Security concerns if misconfigured',
    ],
  },
  {
    id: '6',
    name: 'PostgreSQL',
    slug: 'postgresql',
    description: 'The world\'s most advanced open source relational database',
    longDescription:
      'PostgreSQL is a powerful, open source object-relational database system with over 35 years of active development.',
    category: 'database',
    websiteUrl: 'https://www.postgresql.org',
    githubUrl: 'https://github.com/postgres/postgres',
    avgRating: 4.9,
    totalReviews: 1423,
    pros: [
      'ACID compliant and rock-solid reliability',
      'Rich feature set: JSONB, full-text search, GIS',
      'Excellent performance with proper indexing',
      'Active community and great documentation',
      'Free and open source',
    ],
    cons: [
      'Configuration tuning required for performance',
      'More complex than SQLite for simple apps',
      'Horizontal scaling requires extra tools',
    ],
  },
  {
    id: '11',
    name: 'Vue.js',
    slug: 'vuejs',
    description: 'The progressive JavaScript framework for building UIs',
    longDescription: 'Vue.js is an approachable, performant and versatile framework for building web user interfaces.',
    category: 'frontend',
    websiteUrl: 'https://vuejs.org',
    githubUrl: 'https://github.com/vuejs/core',
    avgRating: 4.5,
    totalReviews: 634,
    pros: [
      'Gentle learning curve',
      'Excellent two-way data binding',
      'Single File Components are clean',
      'Great official ecosystem (Vue Router, Pinia)',
    ],
    cons: [
      'Smaller ecosystem than React',
      'Less job market demand than React',
      'Options vs Composition API confusion',
    ],
  },
  {
    id: '12',
    name: 'Firebase',
    slug: 'firebase',
    description: 'App development platform by Google with realtime database and hosting',
    longDescription: 'Firebase is a platform developed by Google for creating mobile and web applications.',
    category: 'backend',
    websiteUrl: 'https://firebase.google.com',
    githubUrl: 'https://github.com/firebase/',
    avgRating: 4.3,
    totalReviews: 1102,
    pros: [
      'Very fast to prototype with',
      'Realtime database is impressive',
      'Easy authentication setup',
      'Good free tier for small apps',
    ],
    cons: [
      'Vendor lock-in to Google ecosystem',
      'Costs can spike unexpectedly at scale',
      'NoSQL Firestore can be limiting',
      'Querying capabilities are weak',
    ],
  },
  {
    id: '13',
    name: 'Express.js',
    slug: 'expressjs',
    description: 'Fast, unopinionated, minimalist web framework for Node.js',
    longDescription: 'Express is a minimal and flexible Node.js web application framework that provides a robust set of features for web and mobile applications.',
    category: 'backend',
    websiteUrl: 'https://expressjs.com',
    githubUrl: 'https://github.com/expressjs/express',
    avgRating: 4.4,
    totalReviews: 876,
    pros: [
      'Extremely lightweight and fast',
      'Massive middleware ecosystem',
      'Simple and intuitive API',
      'Great for microservices',
    ],
    cons: [
      'No built-in structure — you decide everything',
      'Lacks built-in TypeScript support',
      'Middleware ordering bugs are hard to debug',
    ],
  },
  {
    id: '14',
    name: 'MongoDB',
    slug: 'mongodb',
    description: 'A document-based NoSQL database for flexible data modeling',
    longDescription: 'MongoDB is a source-available cross-platform document-oriented database program.',
    category: 'database',
    websiteUrl: 'https://www.mongodb.com',
    githubUrl: 'https://github.com/mongodb/mongo',
    avgRating: 4.2,
    totalReviews: 987,
    pros: [
      'Flexible schema for rapid development',
      'Easy horizontal sharding',
      'JSON-like documents feel natural',
    ],
    cons: [
      'No transactions in older versions',
      'Memory hungry',
      'ACID compliance not always guaranteed',
    ],
  },
  {
    id: '15',
    name: 'Redis',
    slug: 'redis',
    description: 'In-memory data structure store used as cache, message broker, and database',
    longDescription: 'Redis is an open source in-memory data structure store used as a database, cache, message broker, and streaming engine.',
    category: 'database',
    websiteUrl: 'https://redis.io',
    githubUrl: 'https://github.com/redis/redis',
    avgRating: 4.7,
    totalReviews: 654,
    pros: [
      'Blazing fast — microsecond latency',
      'Rich data structures (lists, sets, sorted sets)',
      'Built-in pub/sub messaging',
      'Persistence options available',
    ],
    cons: [
      'Data limited to available RAM',
      'Not suitable as primary database',
      'Cluster setup is complex',
    ],
  },
  {
    id: '16',
    name: 'Kubernetes',
    slug: 'kubernetes',
    description: 'Production-grade container orchestration platform by Google',
    longDescription: 'Kubernetes (K8s) is an open-source system for automating deployment, scaling, and management of containerized applications.',
    category: 'devops',
    websiteUrl: 'https://kubernetes.io',
    githubUrl: 'https://github.com/kubernetes/kubernetes',
    avgRating: 4.4,
    totalReviews: 543,
    pros: [
      'Industry standard for container orchestration',
      'Auto-scaling and self-healing',
      'Huge ecosystem (Helm, Istio, etc.)',
    ],
    cons: [
      'Steep learning curve',
      'Overkill for small projects',
      'Complex networking model',
    ],
  },
  {
    id: '17',
    name: 'GitHub Actions',
    slug: 'github-actions',
    description: 'Automate your CI/CD workflow directly from GitHub',
    longDescription: 'GitHub Actions makes it easy to automate all your software workflows, now with world-class CI/CD.',
    category: 'devops',
    websiteUrl: 'https://github.com/features/actions',
    githubUrl: 'https://github.com/actions',
    avgRating: 4.6,
    totalReviews: 782,
    pros: [
      'Native GitHub integration — no setup',
      'Huge marketplace of community actions',
      'Free for public repositories',
      'Matrix builds for multiple environments',
    ],
    cons: [
      'YAML syntax can get messy',
      'Limited free minutes for private repos',
      'Debugging failed runs is painful',
    ],
  },
  {
    id: '18',
    name: 'Vercel',
    slug: 'vercel',
    description: 'Platform for frontend frameworks and static sites with serverless functions',
    longDescription: 'Vercel is a cloud platform for static sites and serverless functions that fits perfectly with your workflow.',
    category: 'cloud',
    websiteUrl: 'https://vercel.com',
    avgRating: 4.7,
    totalReviews: 654,
    pros: [
      'Zero-config deployments from Git',
      'Preview deployments for every PR',
      'Excellent performance globally',
      'Great free tier for personal projects',
    ],
    cons: [
      'Expensive for high-traffic projects',
      'Function execution time limits',
      'Vendor lock-in',
    ],
  },
  {
    id: '19',
    name: 'AWS',
    slug: 'aws',
    description: 'Amazon\'s comprehensive cloud computing platform with 200+ services',
    longDescription: 'Amazon Web Services (AWS) is the world\'s most comprehensive and broadly adopted cloud platform.',
    category: 'cloud',
    websiteUrl: 'https://aws.amazon.com',
    avgRating: 4.1,
    totalReviews: 1234,
    pros: [
      'Most comprehensive cloud platform',
      'Unmatched global availability',
      'Mature services and documentation',
    ],
    cons: [
      'Confusing pricing model',
      'Overwhelming number of services',
      'Poor developer experience vs alternatives',
    ],
  },
  {
    id: '23',
    name: 'OpenAI API',
    slug: 'openai',
    description: 'Powerful AI models including GPT-4o, DALL-E, and Whisper',
    longDescription: 'Access GPT-4, DALL-E, Whisper, and other AI models via a clean REST API to add intelligence to your apps.',
    category: 'ai',
    websiteUrl: 'https://platform.openai.com',
    avgRating: 4.6,
    totalReviews: 543,
    pros: [
      'Best-in-class language models',
      'Clean and well-documented API',
      'Fast iteration with new model releases',
      'Embeddings API for semantic search',
    ],
    cons: [
      'Can get expensive at scale',
      'Rate limiting frustrating during development',
      'No on-premise option',
    ],
  },
  {
    id: '24',
    name: 'LangChain',
    slug: 'langchain',
    description: 'Framework for developing LLM-powered applications with chains and agents',
    longDescription: 'LangChain is a framework for developing applications powered by language models.',
    category: 'ai',
    websiteUrl: 'https://langchain.com',
    githubUrl: 'https://github.com/langchain-ai/langchain',
    avgRating: 4.4,
    totalReviews: 432,
    pros: [
      'Abstracts complexity of LLM integrations',
      'Excellent for RAG applications',
      'Supports many LLM providers',
      'Active community and frequent updates',
    ],
    cons: [
      'Abstractions can obscure what\'s happening',
      'Documentation lags behind releases',
      'API changes frequently',
    ],
  },
  {
    id: '25',
    name: 'Jest',
    slug: 'jest',
    description: 'Delightful JavaScript testing framework with a focus on simplicity',
    longDescription: 'Jest is a JavaScript Testing Framework with a focus on simplicity.',
    category: 'testing',
    websiteUrl: 'https://jestjs.io',
    githubUrl: 'https://github.com/jestjs/jest',
    avgRating: 4.5,
    totalReviews: 654,
    pros: [
      'Zero config for most projects',
      'Snapshot testing is powerful',
      'Built-in mocking',
      'Great coverage reports',
    ],
    cons: [
      'Slow on large test suites',
      'ESM support historically painful',
    ],
  },
  {
    id: '26',
    name: 'Cypress',
    slug: 'cypress',
    description: 'Fast, reliable end-to-end testing for anything that runs in a browser',
    longDescription: 'Cypress is a next-generation front end testing tool built for the modern web.',
    category: 'testing',
    websiteUrl: 'https://cypress.io',
    githubUrl: 'https://github.com/cypress-io/cypress',
    avgRating: 4.3,
    totalReviews: 456,
    pros: [
      'Visual test runner is excellent for debugging',
      'Time travel debugging',
      'Fast setup',
    ],
    cons: [
      'Tests run in browser only',
      'Flaky tests in CI environments',
      'Expensive Cloud plan',
    ],
  },
  {
    id: '27',
    name: 'Figma',
    slug: 'figma',
    description: 'Collaborative browser-based interface design and prototyping tool',
    longDescription: 'Figma is a vector graphics editor and prototyping tool which is primarily web-based.',
    category: 'design',
    websiteUrl: 'https://figma.com',
    avgRating: 4.8,
    totalReviews: 1123,
    pros: [
      'Real-time multiplayer collaboration',
      'Works entirely in the browser',
      'Dev Mode for handoff is excellent',
      'Rich plugin ecosystem',
    ],
    cons: [
      'Slow on very large files',
      'Pricing changed drastically after Adobe acquisition attempt',
      'Offline mode limited',
    ],
  },
  {
    id: '28',
    name: 'Storybook',
    slug: 'storybook',
    description: 'Build component libraries and UIs in isolation with interactive docs',
    longDescription: 'Storybook is a frontend workshop for building UI components and pages in isolation.',
    category: 'design',
    websiteUrl: 'https://storybook.js.org',
    githubUrl: 'https://github.com/storybookjs/storybook',
    avgRating: 4.4,
    totalReviews: 567,
    pros: [
      'Perfect for component-driven development',
      'Great for design system documentation',
      'Supports all major frameworks',
    ],
    cons: [
      'Setup time is significant',
      'Slow initial build',
      'Maintainning stories adds overhead',
    ],
  },
]

export const TOOLS_BY_CATEGORY: Record<CategorySlug, Tool[]> = {
  frontend: ALL_TOOLS.filter((t) => t.category === 'frontend'),
  backend: ALL_TOOLS.filter((t) => t.category === 'backend'),
  database: ALL_TOOLS.filter((t) => t.category === 'database'),
  devops: ALL_TOOLS.filter((t) => t.category === 'devops'),
  cloud: ALL_TOOLS.filter((t) => t.category === 'cloud'),
  mobile: ALL_TOOLS.filter((t) => t.category === 'mobile'),
  ai: ALL_TOOLS.filter((t) => t.category === 'ai'),
  testing: ALL_TOOLS.filter((t) => t.category === 'testing'),
  design: ALL_TOOLS.filter((t) => t.category === 'design'),
}

export const FEATURED_TOOLS = ALL_TOOLS.slice(0, 6)

export const TOP_RATED_TOOLS = [...ALL_TOOLS]
  .sort((a, b) => b.avgRating - a.avgRating || b.totalReviews - a.totalReviews)
  .slice(0, 6)

export const MOCK_REVIEWS: Record<string, Review[]> = {
  react: [
    {
      id: 'r1',
      toolSlug: 'react',
      authorUsername: 'minhdev',
      authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=minhdev',
      rating: 5,
      title: 'Absolutely transformed how I build UIs',
      content:
        "React's component model clicked for me immediately. The ecosystem is massive and hooks made everything so much more elegant. I've been using it for 4 years and still learn something new regularly. The DevTools are best-in-class.",
      createdAt: '2025-11-14',
      upvotes: 234,
    },
    {
      id: 'r2',
      toolSlug: 'react',
      authorUsername: 'sarah_codes',
      authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah_codes',
      rating: 4,
      title: 'Great, but the ecosystem fragmentation is real',
      content:
        "React itself is excellent, but you end up choosing from 5 different state management solutions, 3 routing libraries, and the debates about them never end. Once you settle on your stack it's incredible though.",
      createdAt: '2025-10-28',
      upvotes: 187,
    },
    {
      id: 'r3',
      toolSlug: 'react',
      authorUsername: 'tuan_fullstack',
      authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tuan_fullstack',
      rating: 5,
      title: 'The de facto standard for good reason',
      content:
        "I've tried Vue, Svelte, Solid — React remains my default. The job market, the tooling, the community answers. TypeScript integration is now first-class and the new compiler in React 19 is a game changer.",
      createdAt: '2025-12-03',
      upvotes: 312,
    },
    {
      id: 'r4',
      toolSlug: 'react',
      authorUsername: 'beginner_dev',
      authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=beginner_dev',
      rating: 3,
      title: 'Steep learning curve for beginners',
      content:
        'Coming from vanilla JS the mental shift to thinking in components was hard. JSX confused me, then hooks confused me, then useEffect confused me. The docs have improved a lot but still overwhelming at first.',
      createdAt: '2025-09-15',
      upvotes: 98,
    },
  ],
  postgresql: [
    {
      id: 'p1',
      toolSlug: 'postgresql',
      authorUsername: 'db_wizard',
      authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=db_wizard',
      rating: 5,
      title: 'The only database I trust for production',
      content:
        "35+ years of development shows. ACID compliance, JSONB for flexibility when you need it, full-text search built in, PostGIS for geospatial. I've run Postgres on systems handling billions of rows without issues.",
      createdAt: '2025-11-22',
      upvotes: 445,
    },
    {
      id: 'p2',
      toolSlug: 'postgresql',
      authorUsername: 'backend_nguyen',
      authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=backend_nguyen',
      rating: 5,
      title: 'Once you go Postgres you never go back',
      content:
        'The combination of relational integrity and JSONB columns means I never have to choose between SQL and NoSQL. Row-level security for multi-tenant apps is incredible. The extensions ecosystem is phenomenal.',
      createdAt: '2025-12-01',
      upvotes: 289,
    },
    {
      id: 'p3',
      toolSlug: 'postgresql',
      authorUsername: 'ops_engineer',
      authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ops_engineer',
      rating: 4,
      title: 'Excellent but needs tuning',
      content:
        "Out of the box defaults are conservative. You need to tune shared_buffers, effective_cache_size, and max_connections for any real workload. Once properly configured it's rock solid. PgBouncer for connection pooling is a must.",
      createdAt: '2025-10-10',
      upvotes: 156,
    },
  ],
  supabase: [
    {
      id: 's1',
      toolSlug: 'supabase',
      authorUsername: 'indie_hacker',
      authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=indie_hacker',
      rating: 5,
      title: 'Launched my SaaS in a weekend',
      content:
        "Supabase gave me auth, database, storage, and realtime in one package. I launched my SaaS MVP in a single weekend. The dashboard is polished, the docs are excellent, and the free tier is genuinely useful.",
      createdAt: '2025-11-05',
      upvotes: 321,
    },
    {
      id: 's2',
      toolSlug: 'supabase',
      authorUsername: 'fullstack_le',
      authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=fullstack_le',
      rating: 5,
      title: 'Firebase killer — for real this time',
      content:
        "The killer feature is it's actual Postgres underneath. So you get all the benefits of a managed backend PLUS you can do complex SQL queries when you need to. RLS policies are hard to learn but worth it.",
      createdAt: '2025-10-20',
      upvotes: 278,
    },
    {
      id: 's3',
      toolSlug: 'supabase',
      authorUsername: 'startup_cto',
      authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=startup_cto',
      rating: 4,
      title: 'Great for startups, watch the pricing at scale',
      content:
        'Perfect for early-stage where you need to move fast. Hit some limitations around 50k users — had to migrate to a dedicated compute plan. Still cheaper than rolling your own infra, but budget for growth.',
      createdAt: '2025-09-30',
      upvotes: 145,
    },
  ],
  'tailwind-css': [
    {
      id: 't1',
      toolSlug: 'tailwind-css',
      authorUsername: 'ui_dev_phuong',
      authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ui_dev_phuong',
      rating: 5,
      title: 'Completely changed how I write CSS',
      content:
        "I was a CSS-in-JS person before Tailwind. Now I can't imagine going back. The constraint-based design system forces consistency. IntelliSense in VS Code makes discovery instant. Production bundles are tiny.",
      createdAt: '2025-11-18',
      upvotes: 267,
    },
    {
      id: 't2',
      toolSlug: 'tailwind-css',
      authorUsername: 'css_purist',
      authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=css_purist',
      rating: 3,
      title: 'Productivity boost at the cost of readability',
      content:
        "I understand the appeal but 30-class HTML elements hurt my soul. I use it because the team standardized on it and productivity is genuinely higher, but I miss the semantic clarity of BEM or CSS modules.",
      createdAt: '2025-10-05',
      upvotes: 134,
    },
  ],
  docker: [
    {
      id: 'd1',
      toolSlug: 'docker',
      authorUsername: 'devops_tran',
      authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=devops_tran',
      rating: 5,
      title: 'The foundation of modern DevOps',
      content:
        "Docker solved the 'it works on my machine' problem once and for all. Multi-stage builds keep images lean. Docker Compose made local dev environments trivial to share. Can't imagine a world without containers now.",
      createdAt: '2025-11-28',
      upvotes: 389,
    },
    {
      id: 'd2',
      toolSlug: 'docker',
      authorUsername: 'mac_dev',
      authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mac_dev',
      rating: 3,
      title: 'Docker Desktop on Mac is a resource hog',
      content:
        "On Linux it's perfect. On Mac, Docker Desktop eats 2GB RAM just idling. Switched to OrbStack and that problem went away. The containerization concept itself is irreplaceable — just pick your runtime carefully.",
      createdAt: '2025-09-12',
      upvotes: 201,
    },
  ],
}

export const MOCK_USER: User = {
  username: 'johndoe',
  name: 'John Doe',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=johndoe',
  bio: 'Full-stack developer passionate about open source and building great developer tools.',
  joinedDate: 'January 2024',
  reviewsCount: 23,
  totalUpvotesReceived: 156,
}
